
import { useState } from 'react';
import type { ApiResult, UiTranslations } from '../types';
import { 
  LoadingSpinner, 
  RefreshIcon, 
  CopyIcon, 
  GlobeIcon, 
  DownloadIcon, 
  ChartLineIcon,
  EamsTextLogo
} from './Icons';

interface ContentDisplayProps {
  isLoading: boolean;
  result: ApiResult | null;
  error: string | null;
  vertical: string | null;
  onUpdateReport: () => void;
  translations: UiTranslations;
  isEnglishMode: boolean;
  onToggleLanguage: () => void;
  marketCode: string;
}

const SpecificReportStyles = () => (
  <style>{`
    #report-container {
      font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif !important;
      color: #000000 !important;
      -webkit-font-smoothing: antialiased !important;
      text-rendering: optimizeLegibility !important;
      background-color: #ffffff !important;
    }
    #report-container h1, 
    #report-container h2, 
    #report-container h3, 
    #report-container p, 
    #report-container li,
    #report-container span {
      font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif !important;
    }
    #report-container h2 {
      color: #0064D2 !important;
      border-bottom: 2px solid #E5E7EB !important;
      padding-bottom: 8px !important;
      margin-top: 32px !important;
      margin-bottom: 16px !important;
      page-break-after: avoid !important;
      font-size: 1.875rem !important;
      font-weight: 800 !important;
    }
    #report-container h3 {
      display: flex;
      align-items: center;
      margin-top: 20px !important;
      margin-bottom: 10px !important;
      font-size: 1.25rem !important;
      font-weight: 700 !important;
    }
    #report-container p, #report-container li {
      color: #000000 !important;
      font-weight: 500 !important;
      line-height: 1.6 !important;
      margin-bottom: 0.75rem !important;
    }
    #report-container .demand-up { color: #059669 !important; }
    #report-container .demand-down { color: #dc2626 !important; }
    
    #report-container .demand-icon-up { color: #059669 !important; }
    #report-container .demand-icon-down { color: #dc2626 !important; }
    
    #report-container ul {
      margin-bottom: 1.5rem !important;
    }
    
    @media print {
      .pdf-only { display: flex !important; }
    }
  `}</style>
);

function AppFooter({ text }: { text: string }) {
  return (
    <footer className="text-center py-8 mt-8 border-t border-gray-200" data-html2canvas-ignore>
      <p className="text-sm text-gray-500 mb-2">
        {text} <span className="font-bold text-gray-700">eAMS Marketpulse</span>
      </p>
      <p className="text-xs text-gray-400 max-w-2xl mx-auto px-4 italic">
        Disclaimer: This report is generated by AI using real-time search data for strategic planning. 
        Specific financial decisions should be verified with official eBay data sources.
      </p>
    </footer>
  );
}

function InitialState({ t }: { t: UiTranslations }) {
  return (
    <div className="flex flex-col items-center justify-center h-full text-center text-gray-800 p-8 animate-fade-in">
      <div className="flex-grow flex flex-col items-center justify-center">
        <div className="w-full max-w-lg flex flex-col items-center">
          <img src="/images/welcome-page.png" alt="eAMS Marketpulse" className="w-full h-auto object-contain" />
        </div>
        <div className="mt-4 max-w-2xl">
          <h2 className="text-3xl font-bold text-black">{t.welcomeTitle}</h2>
          <p className="mt-4 text-xl font-medium text-gray-900">{t.welcomeIntro}</p>
          <p className="mt-2 text-lg text-gray-900">{t.welcomeInstruction}</p>
        </div>
      </div>
      <AppFooter text={t.footerText} />
    </div>
  );
}

function LoadingState({ vertical, message }: { vertical: string; message: string }) {
  return (
    <div className="flex flex-col items-center justify-center h-full text-center text-gray-800 p-8">
      <LoadingSpinner />
      <p className="mt-4 text-xl font-medium text-gray-600">{message}</p>
      <p className="text-2xl font-bold text-primary-700">{vertical}...</p>
    </div>
  );
}

function ReportDisplay({
  result,
  vertical,
  isLoading,
  onUpdateReport,
  t,
  marketCode
}: {
  result: ApiResult;
  vertical: string;
  isLoading: boolean;
  onUpdateReport: () => void;
  t: UiTranslations;
  marketCode: string;
}) {
  const [isCopied, setIsCopied] = useState(false);

  const handleCopy = () => {
    if (result?.text) {
      navigator.clipboard.writeText(result.text);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2500);
    }
  };

  const handleDownloadPDF = () => {
    const element = document.getElementById('report-container');
    const opt = {
      margin: [10, 10, 10, 10], 
      filename: `${marketCode}_${vertical.replace(/\s+/g, '_')}_Report.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { 
        scale: 2, 
        useCORS: true, 
        logging: false,
        letterRendering: true,
        allowTaint: false
      },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };
    if (typeof window !== 'undefined' && (window as any).html2pdf) {
      (window as any).html2pdf().set(opt).from(element).save();
    }
  };

  const getFormattedDateTime = () => {
    const date = result.lastUpdated || new Date();
    const locale = marketCode === 'US' ? 'en-US' : 'en-GB';
    return date.toLocaleString(locale, { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' });
  };

  const renderFormattedText = (text: string) => {
    const lines = text.split('\n');
    const elements: React.ReactNode[] = [];
    let listItems: string[] = [];
    let currentH2: string = '';

    const flushList = () => {
      if (listItems.length > 0) {
        elements.push(
          <ul key={`ul-${elements.length}`} className="list-disc space-y-2 pl-8 mb-6 text-black marker:text-gray-400 font-medium">
            {listItems.map((item, j) => (
              <li key={j} className="text-black">{item}</li>
            ))}
          </ul>
        );
        listItems = [];
      }
    };

    lines.forEach((line, i) => {
      const trimmedLine = line.trim();

      if (trimmedLine.startsWith('### ')) {
        flushList();
        const content = trimmedLine.substring(4);
        const lowerContent = content.toLowerCase();
        
        const upKeywords = ['increase', 'stieg', 'hausse', 'aumento', 'stijging', 'wzrost', 'nachfrage'];
        const downKeywords = ['decrease', 'drop', 'fall', 'rückgang', 'baisse', 'calo', 'daling', 'spadek', 'rückgang'];

        const isIncrease = upKeywords.some(kw => lowerContent.includes(kw));
        const isDecrease = downKeywords.some(kw => lowerContent.includes(kw));

        const isTakeawaySection = currentH2.toLowerCase().includes('takeaway') || currentH2.toLowerCase().includes('advice') || currentH2.toLowerCase().includes('handlungsempfehlung');

        if (!isTakeawaySection && (isIncrease || isDecrease)) {
            elements.push(
              <h3 key={i} className={`text-xl font-bold mt-8 mb-3 ${isIncrease ? 'demand-up' : 'demand-down'}`}>
                <ChartLineIcon className={`w-5 h-5 mr-2 ${isIncrease ? 'demand-icon-up' : 'demand-icon-down'}`} />
                {content}
              </h3>
            );
        } else {
            elements.push(<h3 key={i} className="text-xl font-bold mt-8 mb-3 text-black">{content}</h3>);
        }
      } else if (trimmedLine.startsWith('## ')) {
        flushList();
        currentH2 = trimmedLine.substring(3);
        elements.push(<h2 key={i} className="text-2xl font-extrabold mb-4 text-black first:mt-0 mt-8">{currentH2}</h2>);
      } else if (trimmedLine.startsWith('* ') || trimmedLine.startsWith('- ')) {
        listItems.push(trimmedLine.replace(/^[-*]\s*/, ''));
      } else if (trimmedLine === '') {
        flushList();
      } else {
        flushList();
        const isActionableHeader = trimmedLine.startsWith('**') && trimmedLine.endsWith('**');
        elements.push(
          <p key={i} className={`mb-4 text-black font-medium leading-relaxed ${isActionableHeader ? 'text-lg font-bold' : ''}`}>
            {trimmedLine}
          </p>
        );
      }
    });

    flushList();
    return elements;
  };

  return (
    <div key={vertical} className="animate-fade-in pb-12">
      <SpecificReportStyles />
      <div id="report-container" className="bg-white min-h-full overflow-x-hidden">
        <div className="md:flex justify-between items-center mb-4 p-6 bg-slate-50 border-b border-slate-200 gap-4">
          <div className="flex-shrink flex-grow min-w-0">
            <h1 className="font-black text-black leading-tight">
              <span className="block text-2xl lg:text-4xl mb-1 truncate">{vertical}</span>
              <span className="block text-xl lg:text-2xl text-gray-700 opacity-90">{t.reportTitleSuffix}</span>
            </h1>
            <div className="flex flex-wrap gap-2 text-xs lg:text-sm font-bold mt-3">
               <span className="bg-white px-3 py-1.5 rounded shadow-sm border border-slate-200 text-primary-700">Market: {marketCode}</span>
               <span className="bg-white px-3 py-1.5 rounded shadow-sm border border-slate-200">{getFormattedDateTime()}</span>
            </div>
          </div>
          
          <div className="flex flex-row items-center gap-4 flex-shrink-0">
            <div className="flex-shrink-0 flex items-center justify-center mr-2">
               {/* Updated to EamsTextLogo */}
               <EamsTextLogo className="drop-shadow-sm" width={150} height={60} />
            </div>

            <div className="flex flex-row items-center gap-1.5" data-html2canvas-ignore>
              <button onClick={handleCopy} className="flex items-center justify-center px-3 lg:px-4 py-2 bg-slate-700 text-white font-bold rounded-lg shadow-sm hover:bg-slate-800 transition-all whitespace-nowrap text-xs lg:text-sm">
                <CopyIcon className="w-3.5 h-3.5 lg:w-4 lg:h-4 mr-1.5" /> {isCopied ? t.copiedButton : t.copyButton}
              </button>
               <button onClick={handleDownloadPDF} className="flex items-center justify-center px-3 lg:px-4 py-2 bg-green-600 text-white font-bold rounded-lg shadow-sm hover:bg-green-700 transition-all whitespace-nowrap text-xs lg:text-sm">
                <DownloadIcon className="w-3.5 h-3.5 lg:w-4 lg:h-4 mr-1.5" /> {t.downloadButton}
              </button>
              <button onClick={onUpdateReport} disabled={isLoading} className="flex items-center justify-center px-3 lg:px-4 py-2 bg-primary-600 text-white font-bold rounded-lg shadow-sm hover:bg-primary-700 transition-all whitespace-nowrap text-xs lg:text-sm">
                <RefreshIcon className={`w-3.5 h-3.5 lg:w-4 lg:h-4 mr-1.5 ${isLoading ? 'animate-spin' : ''}`} /> {t.updateButton}
              </button>
            </div>
          </div>
        </div>

        <article className="max-w-none bg-white px-8 md:px-16 py-8 mx-auto text-black font-medium text-lg leading-relaxed max-w-5xl">
          {renderFormattedText(result.text)}
        </article>

        {result.sources.length > 0 && (
          <div className="mt-12 px-8 pb-12 max-w-5xl mx-auto">
            <h2 className="text-2xl font-black text-black mb-8 flex items-center">
              <GlobeIcon className="w-7 h-7 mr-3 text-primary-500" />
              {t.sourcesTitle}
            </h2>
            <div className="bg-slate-50 p-10 rounded-2xl border border-gray-200 shadow-inner">
              <ul className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {result.sources.map((source, index) => (
                  source.web && <li key={index} className="flex items-start bg-white p-5 rounded-xl shadow-sm border border-gray-100 hover:border-primary-300 transition-colors">
                    <a href={source.web.uri} target="_blank" rel="noopener noreferrer" className="text-primary-700 hover:text-primary-900 transition-colors break-words font-bold text-sm leading-tight">
                      {source.web.title || source.web.uri}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}
        <AppFooter text={t.footerText} />
      </div>
    </div>
  );
}

export function ContentDisplay({
  isLoading,
  result,
  error,
  vertical,
  onUpdateReport,
  translations,
  isEnglishMode,
  onToggleLanguage,
  marketCode
}: ContentDisplayProps) {
  // Updated showLanguageToggle to exclude Ireland (IE) and other primarily English-speaking markets
  const showLanguageToggle = !['UK', 'US', 'AU', 'IE', 'CA', 'SG', 'MY', 'PH', 'HK'].includes(marketCode);
  
  return (
    <main className="w-full md:w-3/4 lg:w-4/5 p-0 bg-slate-100 overflow-y-auto h-screen relative">
      {showLanguageToggle && (
        <div className="absolute top-6 right-6 z-10" data-html2canvas-ignore>
          <button onClick={onToggleLanguage} className="flex items-center bg-white px-5 py-2.5 rounded-full shadow-lg border border-gray-200 text-sm font-bold text-gray-700 hover:bg-gray-50 transition-all active:scale-95">
            <GlobeIcon className="w-5 h-5 mr-2 text-primary-500" /> {isEnglishMode ? "Switch to Native" : "Switch to English"}
          </button>
        </div>
      )}
      {isLoading && !result ? (
        <LoadingState vertical={vertical!} message={translations.loadingMessage} />
      ) : error ? (
        <div className="flex items-center justify-center h-full"><div className="bg-red-50 p-10 rounded-2xl border border-red-200 text-center max-w-lg shadow-xl"><h3 className="text-2xl font-black text-red-700 mb-4">{translations.errorMessage}</h3><p className="text-red-600 font-semibold">{error}</p></div></div>
      ) : result && vertical ? (
        <ReportDisplay result={result} vertical={vertical} isLoading={isLoading} onUpdateReport={onUpdateReport} t={translations} marketCode={marketCode} />
      ) : (
        <InitialState t={translations} />
      )}
    </main>
  );
}
